services:
  demo_db:
    image: "postgres:15"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demodb
      POSTGRES_DB: demo
    volumes:
      - demodb:/data/postgres-demo
    ports:
      - "5432:5432"
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - demo_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://demo_db:5432/demo'

volumes:
  demodb: