spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:55432/demo
    username: postgres
    password: demodb
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
deposit:
  interest: 10
  max-interest: 207