services:
  postgres:
    image: "postgres:15"
    container_name: postgres_demo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demodb
      POSTGRES_DB: demo
    volumes:
      - demodb:/data/postgres-demo
    ports:
      - "55432:5432"
volumes:
  demodb: